from datetime import datetime, timezone
from typing import List, Optional
from pydantic import BaseModel, Field

from app.schemas.review import FindingReviewResponse


class EvidenceCitation(BaseModel):
    """Source-grounded evidence provenance citation for a finding."""

    evidence_id: str
    original_filename: str
    page_number: Optional[int] = Field(None, ge=1)
    char_start: Optional[int] = Field(None, ge=0)
    char_end: Optional[int] = Field(None, ge=0)
    trigger_raw_text: str
    event_id: Optional[str] = None


class FieldDifference(BaseModel):
    """Structured divergence comparison between two source assertions."""

    field: str
    value_a: str
    source_a: str
    value_b: str
    source_b: str


class FindingResponse(BaseModel):
    """Authoritative, source-grounded finding generated by the reasoning engine."""

    finding_id: str
    case_id: str
    finding_type: str
    title: str
    summary: str
    severity: str = Field(default="MEDIUM", description="LOW, MEDIUM, or HIGH")
    conflict_state: str = Field(
        ...,
        description="DIRECT_CONTRADICTION, POTENTIAL_CONFLICT, CONTEXTUALLY_COMPATIBLE, or INSUFFICIENT_CONTEXT",
    )
    citations: List[EvidenceCitation] = Field(
        ...,
        min_length=1,
        description="Mandatory evidence citations grounding this finding.",
    )
    field_diff: Optional[FieldDifference] = None
    model_confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    model_name: str = Field(default="proofflow-reasoning-engine")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    active_review: Optional["FindingReviewResponse"] = None


class FindingListResponse(BaseModel):
    """Collection envelope for case-scoped findings."""

    items: List[FindingResponse]
    total: int
    case_id: str
